blank_issues_enabled: true
contact_links:
  - name:Ignix UI
    url: https://github.com/mindfiredigital/ignix-ui
    about: A modern, high-performance animated component library built with Radix UI, managed through a pnpm monorepo structure with Turborepo for optimal development experience.