name: "New feature proposal"
description: Suggest an idea for this project
title: "[Feature]:"
labels: [":sparkles: feature request"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve?
      value:
      placeholder: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature?
    validations:
      required: true